# Generated by Django 4.2.2 on 2023-06-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='mycharacter',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='myservise',
            name='icon',
        ),
    ]
