# Generated by Django 4.2.2 on 2023-06-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutme_texnology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
