# Generated by Django 4.2.2 on 2023-06-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_aboutme_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
