# Generated by Django 4.2.2 on 2023-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutme_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
