# Generated by Django 4.2.2 on 2023-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_aboutme_git_aboutme_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='freelance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
