# Generated by Django 4.2.2 on 2023-06-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aboutme_freelance'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcomment',
            name='position',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
