# Generated by Django 4.2.2 on 2023-06-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_clientcomment_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
    ]
