# Generated by Django 4.2.2 on 2023-06-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_clientcomment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworkimage',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='main.mywork'),
        ),
    ]
