# Generated by Django 4.2.2 on 2023-06-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_myworkimage_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactme',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactme',
            name='position',
        ),
    ]
