# Generated by Django 4.2.2 on 2023-06-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_contactme_phone_remove_contactme_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='sub',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
