# Generated by Django 4.2.2 on 2023-06-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contactme_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='google',
            new_name='link',
        ),
        migrations.AddField(
            model_name='social',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
